# node

之前有人问我怎么判断一个对象是不是一个 promise 对象, 我立马就回答用 then 来判断, 也就是:
```
function isPromise (obj) {
  if(obj && obj.then && (Object.prototype.isString.call(obj.then) === '[object Function]')) {
    return true;
  }
  return false;
}
```
因为鸭子模型, 但是有没有更好的办法呢?
刚刚从 java 转过来的人常常会有疑问, 那些回调会不会抢占, 我觉得这是没有理解 js 的回调与事件循环的机理, 像 promise 队列, 基本就是一个
同步队列, 不会抢占顺序的, 函数内部保证原子性.
像在 promise 函数中出现错误, 就是说像这样:
```
new Promise((resolve, reject) => {
  foo.bar();
  resolve();
})
.then(() => {
  console.log('resolve');
}, () => {
  console.log('reject');
});
```
promise 里面报错了, 会将报错报到 reject 函数里面, 注意 then 是返回一个新的 promise 的, 所以 then 函数里面报错了如果没有进行监听的话, 异常
是会被吞掉的.如果里面只能放我们信任的代码, 这根本就是一个纸牌屋.
如果像 promise.resolve 传递一个非 promise 非 thenable 的值会得到一个这个值填充的 promise, 如果传递的一个 promise, 那么会得到一个相同的同一个
promise:
```
var p1 = new Promise();

p2 = Promise.resolve(p1);

p1 === p2
```
有时候使用 Promise.resolve 是为了排除之前说的 csp 的问题.
如果在使用 promise 的时候, 没有设定处理 reject 的函数, 那么会有一个默认的函数顶替的.
而且对于 promise 链来说, 上一个链的错误会丢到下一个链的节点的 reject 函数, 然后这个 reject 函数如果有返回值的话, 那么这个返回值就传给下一个链的节点的 resolve 函数, 相当于又回到成功的节点上.
所谓 catch, 其实并不是想的那个 try catch, 而是一个缩写, 是只传递错误处理函数而不传递成功处理函数的方式.